query {
  __schema {
    types {
      name
      kind
      possibleTypes {
        name
        kind
      }
      fields {
        name
        args {
          name
          type {
            name
            kind
            ofType {
              name 
              kind
              ofType {
                name
                kind
                ofType {
                  name
                  kind
                }
              }
            }
          }
        }
        type {
          name
          kind
          ofType {
            name 
            kind
            ofType {
              name
              kind
              ofType {
                name
                kind
              }
            }
          }
        }
      }
    }
  }
}
